In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [20]:
A = np.array([[2, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [21]:
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [22]:
C = np.array([[2, 3],
              [4, 5],
              [6, 7]])

In [23]:
I3 = np.eye(3)

In [24]:
A@B

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [25]:
B@C

array([[ 92, 116],
       [ 56,  71],
       [ 20,  26]])

In [26]:
A@I3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [27]:
B@I3

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

In [28]:
I3@C

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [29]:
inv_A = np.linalg.inv(A)
inv_A

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [32]:
D = A @ inv_A

In [33]:
np.allclose(D,np.eye(3))

False

In [34]:
E = np.array([[2, 2, 3],
              [-1, 4, -2],
              [3, -2, 1]])

In [35]:
inv_E = np.linalg.inv(E)
F = E @ inv_E
np.allclose(F,np.eye(3))

True

In [40]:
F.round()

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [37]:
F.round()+0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
情境：
有分別裝有 2 公升與 3 公升水的甲﹑乙兩支瓶子，每一輪操作都是先將甲瓶的
水倒出一半到乙瓶﹐然後再將乙瓶的水倒出一半回甲瓶，經過三輪後，甲乙瓶子各有幾公升？

In [28]:
A1 = np.array([[2],
               [3]])
B1 = np.array([[0.75,0.5],
               [0.25,0.5]])
for i in range(3):
    A1 = B1@A1

In [29]:
A1

array([[3.3125],
       [1.6875]])

In [ ]:
甲有 3.3125 公升 乙有 1.6875 公升